//#include<LPC21xx.h>
#define FUNC1 0
#define FUNC2 1
#define FUNC3 2
#define FUNC4 3
#define GPIO_0_0 FUNC1
#define TXD0_0_0 FUNC2
#define PWM1_0_0 FUNC3
#define RSEV_0_0 FUNC4
#define GETPINFUNC(WORD,PIN) \
        (PIN<16) ? ((WORD>>(PIN*2))&3) : ((WORD>>((PIN-16)*2))&3); 
#define CFGPIN(WORD,PIN,FUNC) \
        (WORD=(PIN<16) ? \
				((WORD & ~(3<<(PIN*2))) | (FUNC<<(PIN*2))) : \
        ((WORD & ~(3<<((PIN-16)*2))) | (FUNC<<((PIN-16)*2))));
#define SETBIT(WORD,BITPOS) (WORD|=(1<<BITPOS))
#define CLRBIT(WORD,BITPOS) (WORD&=~(1<<BITPOS))
#define CPLBIT(WORD,BITPOS) (WORD^=(1<<BITPOS))
#define WRITEBIT(WORD,BITPOS,BIT) \
        (WORD=((WORD&~(1<<BITPOS)) | (BIT<<BITPOS)))
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define GPIO_IN 0x00000000
#define GPIO_OUT 0xFFFFFFFF
#define WRITENIBBLE(WORD,STARTBITPOS,NIBBLE) \
        (WORD=(WORD&~(15<<STARTBITPOS)) | (NIBBLE<<STARTBITPOS))
#define READNIBBLE(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&15)
#define WRITEBYTE(WORD,STARTBITPOS,BYTE) \
        (WORD=(WORD&~(255<<STARTBITPOS)) | (BYTE<<STARTBITPOS))
#define READBYTE(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&255)
#define SSETBIT(WORD,BITPOS) (WORD=1<<BITPOS)
#define SCLRBIT SSETBIT
#define WRITEHWORD(WORD,STARTBITPOS,HWORD) \
        (WORD=(WORD&~(0xFFFF<<STARTBITPOS)) | (HWORD<<STARTBITPOS))
#define READWRITEBIT(WORD,WBIT,RBIT)  \
        (WORD=(WORD&~(1<<WBIT))|(((WORD>>RBIT)&1)<<WBIT));
#define READWRITEBIT2(DWORD,WBIT,SWORD,RBIT)   \
        (DWORD=(((DWORD&~(1<<WBIT))|((SWORD>>RBIT)&1)<<WBIT)))

